title: Zachary
description: Hi! Welcome to my homepage.
author: Jiang Zeyu
avatar: /photo.jpg
email: zjiang739@gmail.com
subscribe: false

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

remote_theme: ngzhio/jekyll-theme-hamilton

paginate: 10

social:
  name: Jiang Zeyu
  links:
    - https://scholar.google.com/citations?user=i3Lr8_8AAAAJ&hl=zh-CN
    - https://github.com/the-masses
    - https://www.linkedin.com/in/%E6%B3%BD%E5%AE%87-%E6%B1%9F-9b3885286/

google_site_verification: u4WXQl0Eu66rsQo2kRdCNx

lang: en
