title: Jiang Zeyu's Homepage
url: "https://the-masses.github.io"
baseurl: "/"

markdown: kramdown
# ins_logo: "./img/bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/the-masses"
footer_text: "Page design by Jiang Zeyu"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
#  - name: "Resume"
#    link: "resume.pdf"
#  - name: "Contact"
#    link: "contact"
